import assert from 'node:assert/strict';
import test from 'node:test';
import { createChatSubmissionGate } from '../AI_System_Data/public/assets/js/modules/chatSubmissionGate.js';

function makeGate() {
    let sequence = 0;
    return createChatSubmissionGate(() => `request-${++sequence}`);
}

test('double click shares one in-flight API operation', () => {
    const gate = makeGate();
    assert.equal(gate.begin(), 'request-1');
    assert.equal(gate.begin(), null);
    gate.finish();
});

test('submit and click share one in-flight API operation', () => {
    const gate = makeGate();
    assert.equal(gate.begin(), 'request-1'); // submit
    assert.equal(gate.begin(), null); // click generated by the same operation
    gate.finish();
});

test('repeated Enter shares one in-flight API operation', () => {
    const gate = makeGate();
    assert.equal(gate.begin(), 'request-1');
    assert.equal(gate.begin(), null);
    assert.equal(gate.begin(), null);
    gate.finish();
});

test('error or abort cleanup allows the next operation, including identical text', () => {
    const gate = makeGate();
    assert.equal(gate.begin(), 'request-1');
    gate.finish(); // fetch error / AbortError finally path
    assert.equal(gate.begin(), 'request-2');
    gate.finish();
});
